
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 324377
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: virtual_wallet_development


test:
  <<: *default
  database: virtual_wallet_test


production:
  <<: *default
  database: virtual_wallet_production
  username: virtual_wallet
  password: <%= ENV["VIRTUAL_WALLET_DATABASE_PASSWORD"] %>
